### ISSUE TITLE
Matching dataset to figure

### ISSUE THREAD

**Issue by chrisroadmap** [sarambl/REWRITE2BADC-CSV#1]
Can you remind me which figure 

https://github.com/sarambl/REWRITE2BADC-CSV/blob/main/rewrite2badc_csv/badc_header_temp/badc_header_FaIR_model_hist.csv

relates to? Better still if you can tell me the filename of my original output file that you use!

**Comment by sarambl** [comment]
Hi! So, this is just to add the header to your files from here https://github.com/chrisroadmap/ar6/tree/main/data_output/SSPs
I use these ERFs to get future warming in fig 6.22 and 6.24. 

(I got the impression that both the files I use as input and the ones I plot need to be in this format, so I added info to your files)

**Comment by sarambl** [comment]
Sorry, my bad, that file is for this one https://github.com/chrisroadmap/ar6/blob/main/data_output/AR6_ERF_1750-2019.csv

**Comment by chrisroadmap** [comment]
Ah, no it's my bad! I meant this one:

https://github.com/sarambl/REWRITE2BADC-CSV/blob/main/rewrite2badc_csv/badc_header_temp/badc_header_FaIR_model_warming.csv

**Comment by sarambl** [comment]
ahh! I see, that one is for https://github.com/chrisroadmap/ar6/blob/main/data_output/slcf_warming_ranges.csv this file. I did some more editing there (which I haven't added here yet), because I also ended up splitting it into many files (to be in line with a timeseries format.... )

**Comment by sarambl** [comment]
And I use it in the same figures for the percentiles.

**Comment by sarambl** [comment]
Btw, I had some fixed some unnecessary imports and added the computation for the slcf_warming file in a commit now!

**Comment by chrisroadmap** [comment]
I think this is now sorted!
